language: node_js
node_js:
- '8'
before_install:
install:
- cd ./devops && ./install.sh
- cd ..
cache:
  directories:
  - devops/node_modules
  - ui/node_modules
script:
  - cd ./devops && ./build.sh && cd ..
  - cd ./devops && ./deploy.sh && cd ..