matrix:
  include:
    - language: node_js
      node_js:
      - '8'
      before_install:
      install:
      - ./devops/install.sh
      cache:
        directories:
        - devops/node_modules
        - ui/node_modules
      script:
        - ./devops/build.sh
      after_success:
        - ./devops/deploy.sh

    - language: java
      jdk: oraclejdk8
      sudo: false
      before_cache:
        - rm -f  ./server/.gradle/caches/modules-2/modules-2.lock
        - rm -fr ./server/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - ./server/.gradle/caches/
          - ./server/.gradle/wrapper/
      before_install:
        - pip install --user awscli
        - export PATH=$PATH:$HOME/.local/bin
        - cd server
      before_script:
      script:
        - ./gradlew clean build war
      after_success:
        - ../devops/eb-deploy.sh

