matrix:
  include:
    - language: node_js
      node_js:
      - '8'
      before_install:
      install:
      - ./devops/install.sh
      cache:
        directories:
        - devops/node_modules
        - ui/node_modules
      script:
        - ./devops/build.sh
      deploy:
        - ./devops/deploy.sh

    - language: java
      jdk: oraclejdk8
      before_cache:
        - rm -f  ./server/.gradle/caches/modules-2/modules-2.lock
        - rm -fr ./server/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - ./server/.gradle/caches/
          - ./server/.gradle/wrapper/
      before_install:
        - cd server
#      install:
      before_script:
#      script: